Refer to CHANGELOG.md

diff --git a/hardening/Root Locker/root-locker b/hardening/Root Locker/root-locker
--- a/hardening/Root Locker/root-locker
+++ b/hardening/Root Locker/root-locker
@@ -1,43 +1,40 @@
 #!/bin/bash
 #
-# This script locks and removes the root account's password (if one is set). This
-# prevents users from successfully logging into the root account via su. Note that it
-# doesn't prevent users from becoming root via methods such as sudo su.
+# Name: root-locker.bash
 #
-# Version: v1.0.6
+# Description:
+#   This script locks the root account, preventing users from direct logins as root.
+#
+# Note:
+#   Locking the root account doesn't prevent users from using something like `sudo su`
+#   to gain root access.
+#
+# Version: v1.0.7
 # License: MIT License
 #          Copyright (c) 2020-2024 Hunter T. (StrangeRanger)
 #
 ########################################################################################
-####[ Script Wide Variables ]###########################################################
 
-
-green="$(printf '\033[0;32m')"
-red="$(printf '\033[1;31m')"
-nc="$(printf '\033[0m')"
-
-
-####[ Prepping ]########################################################################
+C_GREEN="$(printf '\033[0;32m')"
+C_RED="$(printf '\033[1;31m')"
+C_NC="$(printf '\033[0m')"
 
 
 ## Check if this script was executed with root privilege.
 if [[ $EUID != 0 ]]; then
-    echo "${red}Please run this script as or with root privilege${nc}" >&2
+    echo "${C_RED}Please run this script as or with root privilege${C_NC}" >&2
     echo -e "\nExiting..."
     exit 1
 fi
 
 
-####[ Main ]############################################################################
-
-
 read -rp "We will now disable the root account. Press [Enter] to continue."
 
 echo "Disabling root account..."
-passwd -dl root || {
-    echo -e "\n${red}Failed to lock the root account${nc}"
+usermod -L root || {
+    echo -e "\n${C_RED}Failed to lock the root account${C_NC}" >&2
     echo -e "\nExiting..."
     exit 1
 }
 
-echo -e "\n${green}The root account has been locked${nc}"
+echo -e "\n${C_GREEN}The root account has been locked${C_NC}"
